# Generated by Django 3.1.1 on 2021-07-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozdevzsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quemSomos', models.CharField(max_length=250)),
                ('visao', models.CharField(max_length=250)),
                ('oqueFazemos', models.CharField(max_length=250)),
            ],
        ),
    ]
