# Generated by Django 3.1.1 on 2021-08-27 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mozdevzsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geral',
            old_name='oqueFazemos',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='embassador',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='geral',
            name='quemSomos',
        ),
        migrations.RemoveField(
            model_name='geral',
            name='visao',
        ),
        migrations.RemoveField(
            model_name='person',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='program',
            name='logo',
        ),
        migrations.AddField(
            model_name='embassador',
            name='img_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='img_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='img_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
