# Generated by Django 3.1.1 on 2021-08-06 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mozdevzsite', '0002_geral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embassador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('site', models.CharField(max_length=250)),
                ('logo', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='geral',
            name='logo',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
