# Generated by Django 3.1.1 on 2021-08-12 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mozdevzsite', '0003_auto_20210806_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('team', models.CharField(choices=[('Administrator', 'admin'), ('Alumni', 'alumn'), ('Embassador', 'Embas')], default='Embassador', max_length=30)),
                ('ocupation', models.CharField(max_length=30)),
                ('picture', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='logo',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
